### ISSUE TITLE
VOTE:  Changes to Governance Model for pandas

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-governance#20]
There is a proposal to change the governance model for `pandas`.  The proposed governance model is described in 2 pull requests:

- https://github.com/pandas-dev/pandas-governance/pull/17 describes the creation of a Steering Committee and the concept of Teams
- https://github.com/pandas-dev/pandas-governance/pull/18 describes the responsibilities of the different Teams

According to the current governance model, 80% of the core team needs to vote on this issue, with at least 2/3 of the votes being in favor.  That means we need the votes of 17 individuals, with a positive vote of 14 members of the core team guaranteeing approval.

The rendered governance documents can be found at:
- Main Governance Document:  https://github.com/pandas-dev/pandas-governance/blob/3b494821873a50fd1bdc8609445fa7d411848fe7/governance.md
- Description of Individual Teams:  https://github.com/pandas-dev/pandas-governance/blob/c0e5c586ed9b6dd95d180eff8a6e482571268fa9/teams.md

Voting will close on August 31, 2024.

Cast your vote in a comment below.
* +1: approve.
* 0: abstain.
* -1: disapprove

@pandas-dev/pandas-core

**Comment by WillAyd** [comment]
+1

**Comment by mroeschke** [comment]
+1

**Comment by alimcmaster1** [comment]
+1

**Comment by fangchenli** [comment]
+1

**Comment by jbrockmendel** [comment]
Abstain

**Comment by lukemanley** [comment]
+1

**Comment by rhshadrach** [comment]
+1

**Comment by datapythonista** [comment]
-1

- Not a fan of the steward comcept and giving non core devs the same voting rights as core devs
- I think the new team definitions are unrealistically complex. In oururrent simpler team structure most teams don't do much in practice, and the ones that work (like finance) is usually a single person doing all the work. We should go into making that simpler and closer to reality, not the opposite
- Feels like a 5+ member steering commitee is inefficient. I'd rather have a 3 people committee that just helps when consensus isn't possible

**Comment by jreback** [comment]
+1

**Comment by attack68** [comment]
+1

Was torn between 0 and +1, actually, thinking similar to Marc that this may be too complex and impractical. In the end I view having the momentum to implement something positive and reacting to or iterating any failures later is more favourable than losing all the momentum and risking not adopting any changes at all.

**Comment by jorisvandenbossche** [comment]
+1

**Comment by TomAugspurger** [comment]
+0

**Comment by twoertwein** [comment]
0

**Comment by lithomas1** [comment]
0

**Comment by MarcoGorelli** [comment]
+1

A few things I'd like to comment on:
- Regarding Marc's comments: my understanding is that stewards only get equal voting rights for changes to the governance model, and not to pdeps or other matters. I think I'm OK with that
- I'm also not sure about some teams, but I don't that having them is harmful
- This wouldn't set the governance model in stone. Things can be revised, and think this is a step in the right direction (for example, I'd like to propose shortening the voting period, but I'll do that separately)

I think this is a positive though, and a good move away from the current BDFL model: Wes hasn't been active in years, and based on his vote he probably doesn't have interest in acting as BDFL anymore anyway

**Comment by datapythonista** [comment]
> * my understanding is that stewards only get equal voting rights for changes to the governance model, and not to pdeps or other matters.

For PDEPs, in the team description it says it's the only team with PDEP voting rights. The steering commitee (except for the first election) and anything else feels like all stewards can vote. So for example people in the CoC team will have voting rights for the steering committee election. Not sure about project expenses since this seems ambiguous if it's fully delegated to the finance team now, or all stewards have a say. But clearly it's not the core dev team who decides who receives a grant anymore for what I understand.

And members of a team are decided by existing members of a team. So, if I was the only member of for example the infrastructure team, I could add a random person to the team, and the person would have voting rights for the steering committe, and possibly decide on the project finances.

I personally don't think this stewards idea, and all the added complexity in the governance, is a step forward. I'd rather keep Wes as the BDFL, even if he prefers this new model. ;)

Anyway, I think people are happy with this and it's virtually approved. I just wanted to clarify that I don't think your first bullet point is a minor thing.

**Comment by jorisvandenbossche** [comment]
Marc, could you move your comment to https://github.com/pandas-dev/pandas-governance/pull/17 ? (I will reply there as well)

**Comment by simonjayhawkins** [comment]
> Anyway, I think people are happy with this and it's virtually approved. I
just wanted to clarify that I don't think your first bullet point is a
minor thing.

IIUC from Irv's post 80% of the core team needs to vote on this issue, with
at least 2/3 of the votes being in favor. We have 4 abstensions and 1
against. Another abstention or negative vote could swing the outcome. Joris
has asked people to vote even if they abstain. I'm reluctant to do so!

**Comment by jorisvandenbossche** [comment]
Procedural note: it seems there is some contradiction between what I said in the email about abstentions (just counting towards quorum, as we do for PDEPs) versus what Irv wrote in the top post. I am currently clarifying that with him. 

(and for more comments or responses on the actual proposal body itself -> https://github.com/pandas-dev/pandas-governance/pull/17)

**Comment by Dr-Irv** [comment]
+1

**Comment by noatamir** [comment]
0

**Comment by jorisvandenbossche** [comment]
@bashtage your second point is a misread, I think (or something not clearly stated), I answered at https://github.com/pandas-dev/pandas-governance/pull/17#issuecomment-2319240650

**Comment by bashtage** [comment]
While I have reservations about the specific implementation. I think the overall idea is needed. Replacing my 0 (abstention) as asked for.

One thing that mich simplify the teams issue would be to let the teams be designated by the steerco as needed.  This is often how non-exec boards operate - they have the power to nominate subcommittees and sometimes delegate authority to them. Subcommittes can often include people who are not on the non-exec board due to special skills or knowledge. 

+1

**Comment by simonjayhawkins** [comment]
-1

The current governance documents allow for changes to be submitted via a GitHub pull request, refined through public comment and review, aiming for community consensus. If this negative vote swings the outcome, the proposal can be modified to address concerns raised by both positive and negative voters, and then voted on again. It might even be beneficial to revisit the proposal, address the ambiguities, and ensure that the governance model is both robust and clear. There should be no risk of losing momentum.

**Comment by attack68** [comment]
One day left until this officially closes. Is it worth reaching out to anyone that hasn't yet voted @phofl @topper-123? 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/p901ncf/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/p901ncf/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


10.00% | 25.00% | 65.00%
-- | -- | --
2 | 5 | 13
-1 | 0 | 1
datapythonista | jrbrockmendel | willAyd
simonjayhawkins | tomaugspurger | mroeschke
  | twoertwein | alimcmaster1
  | lithomas1 | wesm
  | notamir | fangchenli
  |   | lukemanley
  |   | rhshadrach
  |   | jreback
  |   | attack68
  |   | jorisvandenbossche
  |   | marcogorelli
  |   | dr-irv
  |   | bashtage



</body>

</html>

**Comment by noatamir** [comment]
Amending my vote to +1

Recognising that there is no perfect governance model,
I agree with Marco that this is a positive move away from the BDFL model and that it can be improved based on what is helpful and unhelpful in practice.

I know it reads complex at first sight, but I do like how explicit it is. I think this is a great improvement in transparency.

**Comment by phofl** [comment]
This was a hard one :(

+1

Overall, I think this moves us to a better state than what we had before (but barely, I would have voted 0 if abstaining was still an option). I thought about this for the last few weeks and I **really** dislike the following sentence:

> The Steering Committee will itself decide when a circumstance is exceptional.

I strongly hope that we can work on clarifying this better even if the proposal is accepted in the current form. 

Additionally, I am not a fan of

> All members of each Team, except the Code of Conduct Team, are eligible to vote.  

I'd generally be happy with giving newish contributors more agency but making them eligible to vote on the steering council adds weight to that that I am definitely not a fan of.

**Comment by TomAugspurger** [comment]
Revising my vote to a +1.

Given my limited participation recently I don't want to push this too much one way or the other, but overall I do think the proposal is a good one.

**Comment by jbrockmendel** [comment]
IIUC the other 0s changing to 1s mean my 0 is no longer at risk of making the vote fail, so I'm keeping at 0.  IFF that understanding is incorrect then count me as +1.

1) In the future we should find a way to abstain that isn't a de-facto -1.

2) My concern about the [gestures vaguely] governance stuff is that it empowers people who are willing to spend their time in governance meetings and who are willing to wade through or write walls of text.

3) My preferred form of governance is an informal do-ocracy: the people who actually do the work make the decisions.  Both as a matter or principle and because they are more likely to actually understand what's going on.

4) I agree with others who have pointed out that the SC deciding what constitutes an exceptional circumstance is bad design.

**Comment by jorisvandenbossche** [comment]
@jbrockmendel I responded to some of those points in https://github.com/pandas-dev/pandas-governance/pull/17#issuecomment-2329430661 (especially the first one is definitely addressed)

**Comment by jorisvandenbossche** [comment]
With the voting period ended, summarizing the vote:


-1 | 0 | 1
-- | -- | --
2 | 3 | 15
10% | 15% | 75%
-- | -- | --
datapythonista | jrbrockmendel | willAyd
simonjayhawkins | twoertwein | mroeschke
  | lithomas1 | alimcmaster1
  |  | fangchenli
  |   | lukemanley
  |   | rhshadrach
  |   | jreback
  |   | attack68
  |   | jorisvandenbossche
  |   | marcogorelli
  |   | dr-irv
  |   | bashtage
  |   | notamir
  |   | phofl
  |   | tomaugspurger

And in addition a special +1 vote of (the now almost officially retired BDFL) Wes.

With this, the quorum is reached (20/21 voted, >80%) and the required majority of 2/3 is passed, and the proposal is accepted!

Thanks all for voting and engaging in the discussion. With the governance working group we will propose some next steps to transition to the new governance, and also I want to ensure that we are aware of some remaining concerns and will try to follow-up on that.

**Comment by jorisvandenbossche** [comment]
With the vote finalized, closing this issue.
