### ISSUE TITLE
SC Election questions

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas-governance#23]
I have a couple questions / clarifications about the election rules:

1. Are votes public or anonymous?
2. How many individuals does each voter vote for? 1? Or 5 (the size of the council)? Or something else?
3. How are ties broken, in case multiple people have the same number of votes for the 5th slot on the council?

I'm not sure if any of these need to go in the governance document, or if they're just technical details to work out before voting starts.

**Comment by jorisvandenbossche** [comment]
Good questions! For 1 and 3, they are not explicitly mentioned in the governance text (since you are asking), so I don't think we really discussed those aspects properly before. 

My quick thoughts:

> Are votes public or anonymous?

I was assuming anonymous

> How many individuals does each voter vote for? 1? Or 5 (the size of the council)? Or something else?

As many as you want (essentially, everyone you approve of, at least that is how I understand approval voting)

> How are ties broken, in case multiple people have the same number of votes for the 5th slot on the council?

That's a good question. Will try to see if I can find how Python does that

**Comment by jorisvandenbossche** [comment]
> > How are ties broken, in case multiple people have the same number of votes for the 5th slot on the council?
> 
> That's a good question. Will try to see if I can find how Python does that

Quoting from PEP13 for the Python SC election:

> Each core team member can vote for zero or more of the candidates. Voting is performed anonymously. Candidates are ranked by the total number of votes they receive. If a tie occurs, it may be resolved by mutual agreement among the candidates, or else the winner will be chosen at random.

I am fine with following that

**Comment by TomAugspurger** [comment]
Thanks, both those sound sensible to me.
